export const ADD_DEPARTMENT = "ADD_DEPARTMENT"
export const ADD_DEPARTMENT_RES = "ADD_DEPARTMENT_RES"

export const GET_DEPARTMENT = "GET_DEPARTMENT"
export const GET_DEPARTMENT_RES = "GET_DEPARTMENT_RES"