export const ADD_GENERAL_TIME_OFF = "ADD_GENERAL_TIME_OFF"
export const ADD_GENERAL_TIME_OFF_RES = "ADD_GENERAL_TIME_OFF_RES"
export const GET_GENERAL_TIME_OFF = "GET_GENERAL_TIME_OFF"
export const GET_GENERAL_TIME_OFF_RES = "GET_GENERAL_TIME_OFF_RES"
