export const START_INSTANT_MEETING = "START_INSTANT_MEETING"
export const START_INSTANT_MEETING_RES = "START_INSTANT_MEETING_RES"

export const SEND_MEETING_INVITE = "SEND_MEETING_INVITE"
export const SEND_MEETING_INVITE_RES = "SEND_MEETING_INVITE_RES"

export const JOIN_MEETING = "JOIN_MEETING"
export const JOIN_MEETING_RES = "JOIN_MEETING_RES"