export const START_INSTANT_MEETING = "START_INSTANT_MEETING"
export const START_INSTANT_MEETING_RES = "START_INSTANT_MEETING_RES"

export const SEND_MEETING_INVITE = "SEND_MEETING_INVITE"
export const SEND_MEETING_INVITE_RES = "SEND_MEETING_INVITE_RES"

export const JOIN_MEETING = "JOIN_MEETING"
export const JOIN_MEETING_RES = "JOIN_MEETING_RES"

export const UPDATE_HOST_CONTROL = "UPDATE_HOST_CONTROL"
export const UPDATE_HOST_CONTROL_RES = "UPDATE_HOST_CONTROL_RES"

export const UPDATE_MEET_SETTINGS = "UPDATE_MEET_SETTINGS"
export const UPDATE_MEET_SETTINGS_RES = "UPDATE_MEET_SETTINGS_RES"

export const SCHEDULE_MEETING = "SCHEDULE_MEETING"
export const SCHEDULE_MEETING_RES = "SCHEDULE_MEETING_RES"

export const GET_CALENDAR_MEETING = "GET_CALENDAR_MEETING"
export const GET_CALENDAR_MEETING_RES = "GET_CALENDAR_MEETING_RES"