export const industryTypes = [
    { value: "IT", label: "Information Technology (IT)" },
    { value: "Finance", label: "Finance" },
    { value: "Retail", label: "Retail" },
    { value: "Healthcare", label: "Healthcare" },
    { value: "Education", label: "Education" },
    { value: "Manufacturing", label: "Manufacturing" },
    { value: "Hospitality", label: "Hospitality" },
    { value: "Construction", label: "Construction" },
    { value: "Transportation", label: "Transportation" },
    { value: "Agriculture", label: "Agriculture" },
    { value: "Real Estate", label: "Real Estate" },
    { value: "Energy", label: "Energy" },
    { value: "Telecommunications", label: "Telecommunications" },
    { value: "Entertainment", label: "Entertainment" },
    { value: "Insurance", label: "Insurance" },
    { value: "Automotive", label: "Automotive" },
    { value: "Legal", label: "Legal" },
    { value: "Pharmaceutical", label: "Pharmaceutical" },
    { value: "Non-Profit", label: "Non-Profit" },
    { value: "Government", label: "Government" },
    { value: "Consulting", label: "Consulting" },
    { value: "Media", label: "Media" },
    { value: "Sports", label: "Sports" },
    { value: "Technology", label: "Technology" },
    { value: "Fashion", label: "Fashion" },
    { value: "Food & Beverage", label: "Food & Beverage" },
    { value: "Beauty & Personal Care", label: "Beauty & Personal Care" },
    { value: "Finance/Banking", label: "Finance/Banking" },
    { value: "Supply Chain", label: "Supply Chain" },
    { value: "Waste Management", label: "Waste Management" },
    { value: "Aerospace", label: "Aerospace" },
    { value: "Chemical", label: "Chemical" },
    { value: "Marine", label: "Marine" },
    { value: "Textiles", label: "Textiles" },
    { value: "Publishing", label: "Publishing" },
    { value: "Security", label: "Security" },
    { value: "Architecture", label: "Architecture" },
    { value: "Software", label: "Software" },
    { value: "E-Commerce", label: "E-Commerce" },
    { value: "Cybersecurity", label: "Cybersecurity" },
    { value: "Fintech", label: "Fintech" },
    { value: "Healthtech", label: "Healthtech" },
    { value: "Edtech", label: "Edtech" },
    { value: "Medtech", label: "Medtech" },
    { value: "Biotech", label: "Biotech" },
    { value: "GreenTech", label: "GreenTech" },
    { value: "Agritech", label: "Agritech" },
    { value: "MarTech", label: "MarTech" },
  ];
  