export const ADD_LEAVE_POLICY = "ADD_LEAVE_POLICY"
export const ADD_LEAVE_POLICY_RES = "ADD_LEAVE_POLICY_RES"
export const GET_LEAVE_POLICY = "GET_LEAVE_POLICY"
export const GET_LEAVE_POLICY_RES = "GET_LEAVE_POLICY_RES"
