export const ADD_SHIFT = 'ADD_SHIFT'
export const ADD_SHIFT_RES = 'ADD_SHIFT_RES'

export const GET_ALL_SHIFT = "GET_ALL_SHIFT"
export const GET_ALL_SHIFT_RES = "GET_ALL_SHIFT_RES"

export const DELETE_SHIFT_BY_ID = "DELETE_SHIFT_BY_ID"
export const DELETE_SHIFT_BY_ID_RES = "DELETE_SHIFT_BY_ID_RES"

export const UPDATE_SHIFT_BY_ID = "UPDATE_SHIFT_BY_ID"
export const UPDATE_SHIFT_BY_ID_RES = "UPDATE_SHIFT_BY_ID_RES"

export const GET_USER_BY_USITIVE_HR = "GET_USER_BY_USITIVE_HR"
export const GET_USER_BY_USITIVE_HR_RES = "GET_USER_BY_USITIVE_HR_RES"

export const ADD_SHIFT_BULK_USER = "ADD_SHIFT_BULK_USER"
export const ADD_SHIFT_BULK_USER_RES = "ADD_SHIFT_BULK_USER_RES"

export const ADD_SHIFT_USER_FROM_HR = "ADD_SHIFT_USER_FROM_HR"
export const ADD_SHIFT_USER_FROM_HR_RES = "ADD_SHIFT_USER_FROM_HR_RES"